springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Authentication Service
        url: /api/v1/auth/v3/api-docs
      - name: User Service
        url: /api/v1/users/v3/api-docs
      - name: Search Service
        url: /api/v1/search/v3/api-docs
      - name: Message Service
        url: /api/v1/rooms/v3/api-docs
      - name: Post Service
        url: /api/v1/posts/v3/api-docs
      - name: Interaction Service
        url: /api/v1/comments/v3/api-docs
      - name: File Service
        url: /api/v1/file/v3/api-docs
      - name: Notification Service
        url: /api/v1/notifications/v3/api-docs
      - name: Group Service
        url: /api/v1/groups/v3/api-docs
      - name: Story Service
        url: /api/v1/stories/v3/api-docs